export const LOAD_SHOP_DETAIL = 'LOAD_SHOP_DETAIL';
export const LOAD_MORE_SHOPS = 'LOAD_MORE_SHOPS';
export const REFRESH_SHOPS = 'REFRESH_SHOPS';

export const LOAD_ORDER_DETAIL = 'LOAD_ORDER_DETAIL';
export const LOAD_MORE_ORDERS = 'LOAD_MORE_ORDERS';
export const REFRESH_ORDERS = 'REFRESH_ORDERS';