export const SELECT_HOME_TAB = 'SELECT_HOME_TAB';
export const LOAD_MERCHANT_DETAIL: ='LOAD_MERCHANT_DETAIL';
export const LOAD_MERCHANT_LIST = 'LOAD_MERCHANT_LIST';
export const LOAD_ORDER_DETAIL = 'LOAD_ORDER_DETAIL';
export const LOAD_ORDERS_LIST = 'LOAD_ORDERS_LIST';
export const LOAD_ACCOUNT_DETAIL = 'LOAD_ACCOUNT_DETAIL';